package com.ruoyi.web.service.mall;

import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.aop.framework.ProxyFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.*;
import org.springframework.transaction.annotation.AnnotationTransactionAttributeSource;
import org.springframework.transaction.interceptor.TransactionInterceptor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.mockito.Mockito.*;
import com.ruoyi.web.controller.mall.*;

@EnabledIfSystemProperty(named="tea.friend.integration",matches="true")
class MallFriendMonthlyDatabaseTest {
 static JdbcTemplate jdbc;static MallFriendMonthlyService service;long owner,buyer;Timestamp start,end;Map<String,Object>body;
 static String unique(){return UUID.randomUUID().toString().replace("-","");}
 @BeforeAll static void connect(){DriverManagerDataSource ds=new DriverManagerDataSource("jdbc:mysql://127.0.0.1:33309/tea_friends_20260905?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai","root","");jdbc=new JdbcTemplate(ds);assertEquals("tea_friends_20260905",jdbc.queryForObject("SELECT DATABASE()",String.class));ProxyFactory f=new ProxyFactory(new MallFriendMonthlyService(jdbc));f.setProxyTargetClass(true);f.addAdvice(new TransactionInterceptor(new DataSourceTransactionManager(ds),new AnnotationTransactionAttributeSource()));service=(MallFriendMonthlyService)f.getProxy();}
 long customer(){String u="MONTH_TEST_"+unique();jdbc.update("INSERT INTO mall_customer(nickname,phone,points) VALUES(?,NULL,37)",u);return jdbc.queryForObject("SELECT id FROM mall_customer WHERE nickname=?",Long.class,u);}
 @BeforeEach void fixture(){owner=customer();buyer=customer();long offset=jdbc.queryForObject("SELECT COALESCE(MAX(id),0) FROM mall_friend_period",Long.class)+1;start=Timestamp.valueOf(LocalDate.of(2021,1,1).plusDays(offset*2).atStartOfDay());end=new Timestamp(start.getTime()+86400000);body=new HashMap<>();body.put("title","隔离月榜_"+unique());body.put("startsAt",start.toString());body.put("endsAt",end.toString());body.put("payoutMethod","TEST_CNY");body.put("amounts",Arrays.asList(10,5,0,0,0,0,0,0,0,0));body.put("requestNo",unique());}
 Map<String,Object> action(String action){Map<String,Object>b=new HashMap<>();b.put("action",action);b.put("reason","隔离测试核验原因");b.put("reference","OFFLINE-TEST-REFERENCE");return b;}
 long period(){long p=service.save(body,1);jdbc.update("UPDATE mall_friend_period SET status='OPEN' WHERE id=?",p);return p;}
 long qualify(long owner,long buyer,Timestamp at){jdbc.update("INSERT INTO mall_invite_record(inviter_customer_id,invitee_customer_id,score_active,score_amount,first_qualified_at) VALUES(?,?,1,2.5,?)",owner,buyer,at);return jdbc.queryForObject("SELECT id FROM mall_invite_record WHERE invitee_customer_id=?",Long.class,buyer);}
 long award(long p){service.settle(p,action("SETTLE"),1);return jdbc.queryForObject("SELECT id FROM mall_friend_monthly_award WHERE period_id=? AND customer_id=?",Long.class,p,owner);}
 String status(long a){return jdbc.queryForObject("SELECT status FROM mall_friend_monthly_award WHERE id=?",String.class,a);}
 @Test void tenAmountsRequiredAndRealPaymentUnsupported(){body.put("amounts",Arrays.asList(10));assertThrows(IllegalArgumentException.class,()->service.save(body,1));body.put("amounts",Arrays.asList(10,-1,0,0,0,0,0,0,0,0));assertThrows(IllegalArgumentException.class,()->service.save(body,1));body.put("amounts",Arrays.asList(10,0,0,0,0,0,0,0,0,0));body.put("payoutMethod","WECHAT_PAY");assertThrows(IllegalArgumentException.class,()->service.save(body,1));}
 @Test void saveRetryReturnsSamePeriodAndRejectsChangedPayload(){long p=service.save(body,1);assertEquals(p,service.save(body,1));body.put("title","不同请求配置");assertThrows(IllegalArgumentException.class,()->service.save(body,1));}
 @Test void publishedRulesImmutableAndOverlapsRejected(){long days=jdbc.queryForObject("SELECT COALESCE(MAX(id),0) FROM mall_friend_period",Long.class)+1;Timestamp future=Timestamp.valueOf(LocalDate.now().plusDays(days*3+1).atStartOfDay());body.put("startsAt",future.toString());body.put("endsAt",new Timestamp(future.getTime()+86400000).toString());long p=service.save(body,1);service.publish(p,action("PUBLISH"),1);service.publish(p,action("PUBLISH"),1);body.put("id",p);body.put("versionNo",2);assertThrows(IllegalArgumentException.class,()->service.save(body,1));body.remove("id");body.put("requestNo",unique());long other=service.save(body,1);assertThrows(IllegalArgumentException.class,()->service.publish(other,action("PUBLISH"),1));assertThrows(IllegalArgumentException.class,()->service.settle(p,action("SETTLE"),1));}
 @Test void cutoffIsStartInclusiveEndExclusive(){long p=period();qualify(owner,buyer,start);qualify(owner,customer(),end);qualify(owner,customer(),new Timestamp(start.getTime()-1000));long a=award(p);assertEquals(1,jdbc.queryForObject("SELECT qualified_count FROM mall_friend_monthly_award WHERE id=?",Integer.class,a));}
 @Test void firstQualificationPreventsRefundRebuyBeingCountedInNewPeriod(){long p=period();qualify(owner,buyer,new Timestamp(start.getTime()-86400000));service.settle(p,action("SETTLE"),1);assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_award WHERE period_id=?",Integer.class,p));}
 @Test void deterministicTiesAndTopTenOnly(){long p=period();qualify(owner,buyer,start);for(int i=0;i<11;i++)qualify(customer(),customer(),start);long a=award(p);assertEquals(1,jdbc.queryForObject("SELECT rank_no FROM mall_friend_monthly_award WHERE id=?",Integer.class,a));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_award WHERE period_id=?",Integer.class,p));assertEquals(12,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_period_rank WHERE period_id=?",Integer.class,p));}
 @Test void parallelSettlementCreatesOneSnapshot()throws Exception{long p=period();qualify(owner,buyer,start);parallel(()->service.settle(p,action("SETTLE"),1));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_award WHERE period_id=?",Integer.class,p));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_event WHERE period_id=? AND action='SETTLE'",Integer.class,p));}
 @Test void parallelTestPayoutIsOnceAndDoesNotCreateCashOrPoints()throws Exception{long p=period();qualify(owner,buyer,start);long a=award(p);parallel(()->service.payout(a,action("TEST_PAY"),1));assertEquals("TEST_PAID",status(a));assertEquals(37,jdbc.queryForObject("SELECT points FROM mall_customer WHERE id=?",Integer.class,owner));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_event WHERE award_id=? AND action='TEST_PAY'",Integer.class,a));assertThrows(IllegalArgumentException.class,()->service.acknowledge(a,owner,action("RECEIVED")));}
 @Test void offlineNeedsReferenceAndUserOwnReceipt(){body.put("payoutMethod","OFFLINE_CNY");long p=period();qualify(owner,buyer,start);long a=award(p);Map<String,Object>b=action("RECORD_OFFLINE");b.put("reference","");assertThrows(IllegalArgumentException.class,()->service.payout(a,b,1));b.put("reference","BANK-TEST-0001");service.payout(a,b,1);service.payout(a,b,1);assertEquals("OFFLINE_SENT",status(a));b.put("reference","BANK-TEST-0002");assertThrows(IllegalArgumentException.class,()->service.payout(a,b,1));assertThrows(IllegalArgumentException.class,()->service.acknowledge(a,buyer,action("RECEIVED")));service.acknowledge(a,owner,action("RECEIVED"));service.acknowledge(a,owner,action("RECEIVED"));assertEquals("RECEIVED",status(a));}
 @Test void disputedReceiptRequiresUserConfirmationAndCannotRepay(){body.put("payoutMethod","OFFLINE_CNY");long p=period();qualify(owner,buyer,start);long a=award(p);service.payout(a,action("RECORD_OFFLINE"),1);service.acknowledge(a,owner,action("DISPUTED"));service.reply(a,action("REPLY"),1);assertEquals("DISPUTED",status(a));assertThrows(IllegalArgumentException.class,()->service.payout(a,action("RECORD_OFFLINE"),1));service.acknowledge(a,owner,action("RECEIVED"));assertEquals("RECEIVED",status(a));}
 @Test void refundedBeforeSettlementIsNotRanked(){long p=period();long r=qualify(owner,buyer,start);jdbc.update("UPDATE mall_invite_record SET score_active=0 WHERE id=?",r);service.settle(p,action("SETTLE"),1);assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_monthly_award WHERE period_id=?",Integer.class,p));}
 @Test void refundedSnapshotBlocksPayoutAndClosureRetainsAudit(){long p=period();long r=qualify(owner,buyer,start);long a=award(p);jdbc.update("UPDATE mall_invite_record SET score_active=0 WHERE id=?",r);assertThrows(IllegalArgumentException.class,()->service.payout(a,action("TEST_PAY"),1));assertEquals(true,service.board(p,owner).get("eligibilityChanged"));service.close(p,action("CLOSE"),1);service.close(p,action("CLOSE"),1);assertEquals("CANCELLED",status(a));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mall_friend_period_rank WHERE period_id=?",Integer.class,p));}
 @Test void userListScopedAndDraftInvisible(){long p=period();qualify(owner,buyer,start);award(p);Map<String,Object>mine=service.awards(owner,1,null);assertEquals(1,mine.get("total"));Map<?,?>row=(Map<?,?>)((List<?>)mine.get("rows")).get(0);assertFalse(row.containsKey("customerId"));assertEquals(0,service.awards(buyer,1,null).get("total"));body.put("requestNo",unique());long draft=service.save(body,1);assertThrows(IllegalArgumentException.class,()->service.board(draft,owner));}
 @Test void authenticationRequiredAndAdminPermissionsPresent()throws Exception{MallSessionService sessions=mock(MallSessionService.class);when(sessions.requireMember(null)).thenThrow(new MallAuthenticationException("请登录"));MockMvcBuilders.standaloneSetup(new MallFriendMonthlyController(service,sessions)).build().perform(get("/mall/tea-friends/monthly/awards")).andExpect(org.springframework.test.web.servlet.result.MockMvcResultMatchers.status().isUnauthorized());for(java.lang.reflect.Method m:MallFriendMonthlyAdminController.class.getDeclaredMethods())if(java.lang.reflect.Modifier.isPublic(m.getModifiers()))assertNotNull(m.getAnnotation(PreAuthorize.class),m.getName());}
 static void parallel(Runnable work)throws Exception{ExecutorService pool=Executors.newFixedThreadPool(4);try{List<Future<?>>f=new ArrayList<>();for(int i=0;i<4;i++)f.add(pool.submit(work));for(Future<?>v:f)v.get(20,TimeUnit.SECONDS);}finally{pool.shutdownNow();}}
}
